name: Build and Test
on:
  push:
    branches:
      - "*"
jobs:
  gradle_build_test:
    name: Gradle build and test
    strategy:
      matrix:
#        os: [ ubuntu-latest,macos-latest,windows-latest ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          check-latest: true
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
#        run: chmod +x ./gradlew
        run: chmod +x ./gradlew && ./gradlew build
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: build
      - name: Test with Gradle
#        run: chmod +x ./gradlew
        run: chmod +x ./gradlew && ./gradlew test
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: test